/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testviews;

/**
 *
 * @author tako
 */
public class TestColumnsView extends javax.swing.JPanel {

    /**
     * Creates new form TestOptionsView
     */
    public TestColumnsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x_column_label = new javax.swing.JLabel();
        x_axis_name_label = new javax.swing.JLabel();
        x_axis_type_label = new javax.swing.JLabel();
        y_column_label = new javax.swing.JLabel();
        y_axis_name_label = new javax.swing.JLabel();
        y_axis_type_label = new javax.swing.JLabel();
        x_column_combo_box = new javax.swing.JComboBox();
        x_axis_name_text_field = new javax.swing.JTextField();
        x_axis_type_combo_box = new javax.swing.JComboBox();
        y_column_combo_box = new javax.swing.JComboBox();
        y_axis_name_text_field = new javax.swing.JTextField();
        y_axis_type_combo_box = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        chart_type_label = new javax.swing.JLabel();
        chart_type_combo_box = new javax.swing.JComboBox();
        chart_title_label = new javax.swing.JLabel();
        chart_title_text_field = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        group_by_column_label = new javax.swing.JLabel();
        group_by_column_combo_box = new javax.swing.JComboBox();
        graph_button = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        x_column_label.setText("X Column");

        x_axis_name_label.setText("X Axis Name");

        x_axis_type_label.setText("X Axis Type");

        y_column_label.setText("Y Column");

        y_axis_name_label.setText("Y Axis Name");

        y_axis_type_label.setText("Y Axis Type");

        x_column_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        x_column_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_column_combo_boxActionPerformed(evt);
            }
        });

        x_axis_name_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_axis_name_text_fieldActionPerformed(evt);
            }
        });

        x_axis_type_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Exponential" }));

        y_column_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        y_column_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_column_combo_boxActionPerformed(evt);
            }
        });

        y_axis_type_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Exponential" }));

        chart_type_label.setText("Chart Type");

        chart_type_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XY Graph", "Bar Graph" }));

        chart_title_label.setText("Chart Title");

        chart_title_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chart_title_text_fieldActionPerformed(evt);
            }
        });

        group_by_column_label.setText("Group By Column");

        group_by_column_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));

        graph_button.setText("Graph");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chart_title_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x_axis_name_text_field, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(x_axis_type_combo_box, javax.swing.GroupLayout.Alignment.TRAILING, 0, 220, Short.MAX_VALUE)
                            .addComponent(x_column_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(y_axis_name_text_field, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(y_axis_type_combo_box, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(y_column_combo_box, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(group_by_column_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chart_title_text_field)
                            .addComponent(chart_type_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chart_type_label)
                                    .addComponent(x_column_label)
                                    .addComponent(x_axis_name_label)
                                    .addComponent(x_axis_type_label)
                                    .addComponent(y_column_label)
                                    .addComponent(y_axis_name_label)
                                    .addComponent(y_axis_type_label)
                                    .addComponent(group_by_column_label))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(graph_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart_title_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart_title_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chart_type_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart_type_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(x_column_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x_column_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(x_axis_name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x_axis_name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(x_axis_type_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x_axis_type_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(y_column_label)
                .addGap(4, 4, 4)
                .addComponent(y_column_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(y_axis_name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(y_axis_name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(y_axis_type_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(y_axis_type_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(group_by_column_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group_by_column_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graph_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void y_column_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_column_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y_column_combo_boxActionPerformed

    private void x_column_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_column_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_column_combo_boxActionPerformed

    private void chart_title_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chart_title_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chart_title_text_fieldActionPerformed

    private void x_axis_name_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_axis_name_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_axis_name_text_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chart_title_label;
    private javax.swing.JTextField chart_title_text_field;
    private javax.swing.JComboBox chart_type_combo_box;
    private javax.swing.JLabel chart_type_label;
    private javax.swing.JButton graph_button;
    private javax.swing.JComboBox group_by_column_combo_box;
    private javax.swing.JLabel group_by_column_label;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel x_axis_name_label;
    private javax.swing.JTextField x_axis_name_text_field;
    private javax.swing.JComboBox x_axis_type_combo_box;
    private javax.swing.JLabel x_axis_type_label;
    private javax.swing.JComboBox x_column_combo_box;
    private javax.swing.JLabel x_column_label;
    private javax.swing.JLabel y_axis_name_label;
    private javax.swing.JTextField y_axis_name_text_field;
    private javax.swing.JComboBox y_axis_type_combo_box;
    private javax.swing.JLabel y_axis_type_label;
    private javax.swing.JComboBox y_column_combo_box;
    private javax.swing.JLabel y_column_label;
    // End of variables declaration//GEN-END:variables
}
