package org.plasmagraph.graphs;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPanel;

import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.*;
import org.plasmagraph.template.Template;

public class PieChart extends JFrame{

    
        /**
	 * "Unique" ID generated by Eclipse.
	 * How unique it may be is questionable, but it should work well enough.
	 */
         // Let Eclipse do it.
        JFreeChart chart;
        CategoryDataset imported_data;
	
        // Constructors
	public PieChart (Template t, CategoryDataset d) {
		super(t.chart_name);
                this.imported_data = d;
		setContentPane (createJPanel (t));
	}
	
	private JPanel createJPanel (Template t) {
		chart = createChart (createDataset(t), t);
		ChartPanel c = new ChartPanel (chart, true, true, true, true, true);
                c.setPreferredSize(new Dimension (t.x_minimum, t.y_minimum));
		return (c);
	}
	
	private PieDataset createDataset (Template t) {
		DefaultPieDataset set = new DefaultPieDataset ();
                generateTestDataset (set);
		
		return (set);
	}
	
	private void generateTestDataset(DefaultPieDataset set) {
		set.setValue ("http", new Double (53.2));
		set.setValue ("ftp", new Double (10.0));
		set.setValue ("ssh", new Double (27.5));
		set.setValue ("https", new Double (7.5));
		set.setValue ("telnet", new Double (11.0));
		set.setValue ("rlogin", new Double (19.4));
	}
	
	private JFreeChart createChart (PieDataset set, Template t) {
		JFreeChart c = ChartFactory.createPieChart
                        (t.chart_name, set, t.using_legend, t.using_tooltips, t.generate_urls);
		PiePlot plot = (PiePlot) c.getPlot();
		
		plot.setSectionOutlinesVisible(true);
		plot.setLabelFont(new Font ("SansSerif", Font.PLAIN, 12));
		plot.setCircular(false);
		
		return (c);
	}
}
