package org.plasmagraph.graphs;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPanel;

import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.CategoryToPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.*;
import org.jfree.util.TableOrder;
import org.plasmagraph.sanitizer.ChartConverter;
import org.plasmagraph.template.Template;

public class PieChart extends JFrame{
    /**
	 * "Unique" ID generated by Eclipse.
	 * How unique it may be is questionable, but it should work well enough.
	 */
	private static final long serialVersionUID = 6692735438618471456L;

	private JFreeChart chart;
	private ChartConverter imported_data;
	
    // Constructors
	/* Test Constructor */
	public PieChart (Template t) {
		super(t.chart_name);
		setContentPane (createJPanel (t));
	}
	
    public PieChart (Template t, ChartConverter c) {
		super(t.chart_name);
        this.imported_data = c;
		setContentPane (createJPanel (t));
	}
	
	private JPanel createJPanel (Template t) {
		chart = createChart (createDataset(t), t);
		ChartPanel c = new ChartPanel (chart, true, true, true, true, true);
                c.setPreferredSize(new Dimension (t.x_minimum, t.y_minimum));
		return (c);
	}
	
	private PieDataset createDataset (Template t) {
		return (generateTestDataset()); //(imported_data.toPieDataset(true, 1));
	}
	
	private PieDataset generateTestDataset() {
		DefaultPieDataset set = new DefaultPieDataset ();
		set.setValue("a", (Double) 5.0);
		set.setValue("b", (Double) 25.0);
		set.setValue("c", (Double) 30.0);
		set.setValue("d", (Double) 20.0);
		set.setValue("e", (Double) 20.0);
		return set;
	}

	private JFreeChart createChart (PieDataset set, Template t) {
		JFreeChart c = ChartFactory.createPieChart
                        (t.chart_name, set, t.using_legend, t.using_tooltips, t.generate_urls);
		PiePlot plot = (PiePlot) c.getPlot();
		
		plot.setSectionOutlinesVisible(true);
		plot.setLabelFont(new Font ("SansSerif", Font.PLAIN, 12));
		plot.setCircular(false);
		
		return (c);
	}
}
