package org.plasmagraph.graphs;

// Swing / AWT
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPanel;

// JFreeChart
import org.jfree.chart.*;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.xy.DefaultXYDataset;
// http://www.jfree.org/jfreechart/api/javadoc/org/jfree/data/xy/DefaultXYDataset.html
import org.jfree.data.xy.XYDataset;

// PlasmaGraph
import org.plasmagraph.template.Template;

public class XYPlot extends JFrame{

	/**
	 * "Unique" ID generated by Eclipse.
	 * How unique it may be is questionable, but it should work well enough.
	 */
	private static final long serialVersionUID = -5204846354493237573L;
	JFreeChart chart;
    CategoryDataset imported_data;

	// Constructors
	public XYPlot (Template t, CategoryDataset d) {
		super(t.chart_name);
        this.imported_data = d;
		setContentPane (createJPanel (t));
	}
	
	private JPanel createJPanel (Template t) {
		chart = createChart (createDataset(t), t);
		ChartPanel c = new ChartPanel (chart, true, true, true, true, true);
                c.setPreferredSize(new Dimension (t.x_minimum, t.y_minimum));
		return (c);
	}
	
	private XYDataset createDataset (Template t) {
		DefaultXYDataset set = new DefaultXYDataset ();
		generateTestDataset (set, t);
		
		return (set);
	}
	
	private void generateTestDataset(DefaultXYDataset set, Template t) {
		double[][] data = new double [2][6];
		for (int i = 0; i < 6; ++i) {
                    data[0][i] = i + 1;
                    data[1][i] = i + 1;
		}
		set.addSeries("Set 1", data);
                
                double[][] data2 = new double [2][6];
		for (int i = 0; i < 6; ++i) {
                    data2[0][i] = i + 1;
                    data2[1][i] = 6 - i;
		}
		set.addSeries("Set 2", data2);
	}

	private JFreeChart createChart (XYDataset set, Template t) {
		JFreeChart c = ChartFactory.createScatterPlot(t.chart_name, t.y_axis_name, t.x_axis_name, 
				set, t.orientation, t.using_legend, t.using_tooltips, t.generate_urls);
		
		//org.jfree.chart.plot.XYPlot plot = c.getXYPlot();
		
		return (c);
	}
}
