/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrototypeMainFrame.java
 *
 * Created on Nov 15, 2013, 11:37:29 AM
 */
package org.plasmagraph.prototype;

/**
 *
 * @author tako
 */
public class PrototypeMainFrame extends javax.swing.JFrame {

    /** Creates new form PrototypeMainFrame */
    public PrototypeMainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrototypeMainJPanel = new javax.swing.JPanel();
        PrototypeMainChartTypeComboBox = new javax.swing.JComboBox();
        PrototypeMainChartTypeLabel = new javax.swing.JLabel();
        PrototypeMainOpenTemplateWindowButton = new javax.swing.JButton();
        PrototypeMainMenuBar = new javax.swing.JMenuBar();
        PrototypeMainFile = new javax.swing.JMenu();
        PrototypeMainQuitButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrototypeMainChartTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pie Chart", "Bar Chart", "Line Chart", "XY Plot" }));

        PrototypeMainChartTypeLabel.setText("Chart Type");

        PrototypeMainOpenTemplateWindowButton.setText("Open Template Window");
        PrototypeMainOpenTemplateWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrototypeMainOpenTemplateWindowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrototypeMainJPanelLayout = new javax.swing.GroupLayout(PrototypeMainJPanel);
        PrototypeMainJPanel.setLayout(PrototypeMainJPanelLayout);
        PrototypeMainJPanelLayout.setHorizontalGroup(
            PrototypeMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrototypeMainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrototypeMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrototypeMainOpenTemplateWindowButton)
                    .addGroup(PrototypeMainJPanelLayout.createSequentialGroup()
                        .addComponent(PrototypeMainChartTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PrototypeMainChartTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        PrototypeMainJPanelLayout.setVerticalGroup(
            PrototypeMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrototypeMainJPanelLayout.createSequentialGroup()
                .addGroup(PrototypeMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrototypeMainChartTypeLabel)
                    .addComponent(PrototypeMainChartTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrototypeMainOpenTemplateWindowButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PrototypeMainFile.setText("File");

        PrototypeMainQuitButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        PrototypeMainQuitButton.setText("Quit");
        PrototypeMainQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrototypeMainQuitButtonActionPerformed(evt);
            }
        });
        PrototypeMainFile.add(PrototypeMainQuitButton);

        PrototypeMainMenuBar.add(PrototypeMainFile);

        setJMenuBar(PrototypeMainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrototypeMainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrototypeMainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void PrototypeMainQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrototypeMainQuitButtonActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_PrototypeMainQuitButtonActionPerformed

private void PrototypeMainOpenTemplateWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrototypeMainOpenTemplateWindowButtonActionPerformed
// TODO add your handling code here:
    PrototypeTemplateFrame t_frame = new PrototypeTemplateFrame 
            ((String) this.PrototypeMainChartTypeComboBox.getSelectedItem());
    
    t_frame.pack();
    t_frame.setVisible(true);
    t_frame.setEnabled(true);
    t_frame.setAlwaysOnTop(true);
}//GEN-LAST:event_PrototypeMainOpenTemplateWindowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrototypeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrototypeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrototypeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrototypeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PrototypeMainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PrototypeMainChartTypeComboBox;
    private javax.swing.JLabel PrototypeMainChartTypeLabel;
    private javax.swing.JMenu PrototypeMainFile;
    private javax.swing.JPanel PrototypeMainJPanel;
    private javax.swing.JMenuBar PrototypeMainMenuBar;
    private javax.swing.JButton PrototypeMainOpenTemplateWindowButton;
    private javax.swing.JMenuItem PrototypeMainQuitButton;
    // End of variables declaration//GEN-END:variables
}
